apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1ngnixaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1ngnixaks
  template:
    metadata:
      labels:
        app: app1ngnixaks 
    spec:
      containers:
        - name: app1ngnixaks 
          image: aksdevopsacrrr.azurecr.io/app1ngnixaks
          ports:
          - containerPort: 80